repos:
  - hooks:
      - id: fmt
      - id: cargo-check
      - id: cargo-test
        args: ['--', '--test-threads=1']
      # - id: clippy
    repo: https://github.com/kajmaj87/pre-commit-rust
    rev: v1.0
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]