name: Publish

on:
  push:
    branches: [ "deploy" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    environment: CARGO_REGISTRY_TOKEN

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Publish
      run: cargo publish
